{% set name = "google-cloud-spanner" %}
{% set version = "3.42.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-spanner-{{ version }}.tar.gz
  sha256: 13b6aba86059fd03f36c032c4143274d6883d39e2d32bf753e0ad3d2dcd08e12

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - grpc-interceptor >=0.15.4
    - python >=3.7
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-cloud-core >=1.4.4,<3.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - sqlparse >=0.4.4
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    # libcst extra
    - libcst >=0.2.5
    - deprecated >=1.2.14

test:
  imports:
    - google.cloud
    - google.cloud.spanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-spanner
  summary: Google Cloud Spanner API client library
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: |
    Python Client for Cloud Spanner
    -------------------------

    [Cloud Spanner]() is the world's first fully managed relational database service
    to offer both strong consistency and horizontal scalability for
    mission-critical online transaction processing (OLTP) applications. With Cloud
    Spanner you enjoy all the traditional benefits of a relational database; but
    unlike any other relational database service, Cloud Spanner scales horizontally
    to hundreds or thousands of servers to handle the biggest transactional
    workloads.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/spanner/index.html)
    - [Product Documentation](https://cloud.google.com/spanner/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -----------
    Python >= 3.5

    Deprecated Python Versions
    -----------
    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.dev/python/spanner/latest/index.html
  dev_url: https://github.com/googleapis/python-spanner

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
