{% set name = "google-cloud-spanner" %}
{% set version = "3.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf7e4359d2f2148eda18a11f909813d07e794347a02f56dfbbd544418d30e5b2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.0,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-cloud-core >=1.4.4,<3.0.0
    - grpc-interceptor >=0.15.4
    - grpc-google-iam-v1 >=0.12.4,<1.0.0
    - proto-plus >=1.22.0,<2.0.0
    - sqlparse >=0.4.4
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    # libcst extra
    - libcst >=0.2.5

test:
  imports:
    - google.cloud
    - google.cloud.spanner
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/python-spanner
  summary: Google Cloud Spanner API client library
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://googleapis.dev/python/spanner/latest/index.html
  dev_url: https://github.com/googleapis/python-spanner

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
