schema_version: 1

context:
  name: google-cloud-spanner
  version: 3.62.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a25bdbfda84bc7a819f04e45473187d8670711fd5ec827cf442e3664661d1d23

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-api-core >=1.34.0,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-cloud-core >=1.4.4,<3.0.0
    - grpc-interceptor >=0.15.4
    - grpc-google-iam-v1 >=0.12.4,<1.0.0
    - proto-plus >=1.22.0,<2.0.0
    - sqlparse >=0.4.4
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - opentelemetry-api >=1.22.0
    - opentelemetry-sdk >=1.22.0
    - opentelemetry-semantic-conventions >=0.43b0
    - opentelemetry-resourcedetector-gcp >=1.8.0a0
    - google-cloud-monitoring >=2.16.0
    - mmh3 >=4.1.0
    # libcst extra
    - libcst >=0.2.5

tests:
  - python:
      imports:
        - google.cloud
        - google.cloud.spanner
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Google Cloud Spanner API client library
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/python-spanner
  repository: https://github.com/googleapis/python-spanner
  documentation: https://googleapis.dev/python/spanner/latest/index.html

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
